(() => {
 const activation=location.pathname==='/activate', token=activation?location.hash.slice(1):'';
 if(activation)history.replaceState(null,'',location.pathname);
 const $=id=>document.getElementById(id),form=$('auth-form'),button=$('submit');
 if(activation){$('heading').textContent='Activa tu acceso';$('intro').textContent='Crea una contraseña personal para tu cuenta.';$('username-field').hidden=true;$('username').required=false;$('confirm-field').hidden=false;$('confirm-password').required=true;$('password-help').hidden=false;$('password').minLength=12;$('password').autocomplete='new-password';button.textContent='Guardar contraseña';$('forgot').hidden=true;if(!token){$('error').textContent='Abre el enlace completo que te compartieron.';button.disabled=true;}}
 $('show-password').onclick=()=>{const show=$('password').type==='password';$('password').type=show?'text':'password';$('show-password').textContent=show?'Ocultar':'Ver';$('show-password').setAttribute('aria-label',show?'Ocultar contraseña':'Mostrar contraseña');};
 $('forgot').onclick=()=>{$('recovery-help').hidden=!$('recovery-help').hidden;};
 form.addEventListener('submit',async e=>{e.preventDefault();$('error').textContent='';if(activation&&$('password').value!==$('confirm-password').value){$('error').textContent='Las contraseñas no coinciden.';return;}button.disabled=true;try{const response=await fetch(activation?'/api/auth/activate':'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(activation?{token,password:$('password').value}:{username:$('username').value,password:$('password').value})});const result=await response.json();if(!response.ok)throw new Error(typeof result.detail==='string'?result.detail:'Revisa los datos e inténtalo de nuevo.');if(activation){form.hidden=true;$('heading').textContent='Tu cuenta está lista';$('intro').textContent='Ya puedes entrar con tu usuario y tu nueva contraseña.';const link=document.createElement('a');link.href='/login';link.textContent='Ir al inicio de sesión';$('intro').after(link);}else location.replace('/workspace');}catch(error){$('error').textContent=error.message;}finally{button.disabled=false;}});
})();
