-- ============================================================================
-- FARO: Flujo de Almacén y Reorden Operativo
-- Esquema de Base de Datos para Supabase (PostgreSQL)
-- ============================================================================

-- 1. TABLA DE AUDITORÍAS / LECTURAS DE INVENTARIO
CREATE TABLE IF NOT EXISTS audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    filename TEXT NOT NULL,
    audit_date DATE NOT NULL DEFAULT CURRENT_DATE,
    uploaded_at TIMESTAMPTZ DEFAULT NOW(),
    total_items INTEGER DEFAULT 0,
    total_faltantes INTEGER DEFAULT 0,
    total_sobrantes INTEGER DEFAULT 0,
    total_validados INTEGER DEFAULT 0
);

-- 2. TABLA DE ITEMS DE CADA AUDITORÍA
CREATE TABLE IF NOT EXISTS audit_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id BIGINT NOT NULL REFERENCES audits(id) ON DELETE CASCADE,
    reference TEXT NOT NULL,
    base_reference TEXT,
    name TEXT NOT NULL,
    size TEXT,
    color TEXT,
    barcode TEXT,
    gender TEXT DEFAULT '',
    garment_code TEXT DEFAULT '',
    garment_type TEXT DEFAULT '',
    store_count INTEGER DEFAULT 0,
    warehouse_count INTEGER DEFAULT 0,
    theoretical_count INTEGER DEFAULT 0,
    difference INTEGER DEFAULT 0,
    category TEXT DEFAULT 'General',
    status TEXT DEFAULT 'pendiente', -- 'pendiente', 'validada'
    validation_verdict TEXT DEFAULT '',
    validation_notes TEXT DEFAULT '',
    validated_at TIMESTAMPTZ
);

-- 3. TABLA DEL CATÁLOGO UNIVERSAL DE FOTOS
CREATE TABLE IF NOT EXISTS catalog_photos (
    reference TEXT PRIMARY KEY,
    photo_url TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ÍNDICES DE ALTO RENDIMIENTO PARA CONSULTAS RÁPIDAS
CREATE INDEX IF NOT EXISTS idx_audit_items_audit_id ON audit_items(audit_id);
CREATE INDEX IF NOT EXISTS idx_audit_items_ref ON audit_items(reference);
CREATE INDEX IF NOT EXISTS idx_audit_items_base_ref ON audit_items(base_reference);
CREATE INDEX IF NOT EXISTS idx_audit_items_barcode ON audit_items(barcode);
CREATE INDEX IF NOT EXISTS idx_audits_date ON audits(audit_date DESC);

-- Ejecutar como administrador en el SQL Editor de TU proyecto Supabase.
-- Preparado para backend privado: requiere clave service_role o sb_secret_ SOLO en el servidor.
-- No borra datos. Revoca acceso directo de navegadores anónimos y usuarios no administradores.
BEGIN;
DO $$
DECLARE t text; p record;
BEGIN
  FOREACH t IN ARRAY ARRAY['audits','audit_items','catalog_photos'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated', t);
    EXECUTE format('GRANT ALL ON TABLE public.%I TO service_role', t);
    FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename=t LOOP
      EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, t);
    END LOOP;
  END LOOP;
END $$;
DROP POLICY IF EXISTS "Public View Photos" ON storage.objects;
DROP POLICY IF EXISTS "Public Upload Photos" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Photos" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete Photos" ON storage.objects;
-- El bucket ya contenía Excels: hacerlo privado cierra sus enlaces públicos.
UPDATE storage.buckets SET public = false WHERE id = 'garment-photos';
INSERT INTO storage.buckets (id, name, public) VALUES ('faro-backups','faro-backups',false) ON CONFLICT (id) DO UPDATE SET public=false;
COMMIT;
