-- ============================================================================
-- FARO: Flujo de Almacén y Reorden Operativo
-- Esquema de Base de Datos para Supabase (PostgreSQL)
-- ============================================================================

-- 1. TABLA DE AUDITORÍAS / LECTURAS DE INVENTARIO
CREATE TABLE IF NOT EXISTS audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    filename TEXT NOT NULL,
    audit_date DATE NOT NULL DEFAULT CURRENT_DATE,
    uploaded_at TIMESTAMPTZ DEFAULT NOW(),
    total_items INTEGER DEFAULT 0,
    total_faltantes INTEGER DEFAULT 0,
    total_sobrantes INTEGER DEFAULT 0,
    total_validados INTEGER DEFAULT 0
);

-- 2. TABLA DE ITEMS DE CADA AUDITORÍA
CREATE TABLE IF NOT EXISTS audit_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id BIGINT NOT NULL REFERENCES audits(id) ON DELETE CASCADE,
    reference TEXT NOT NULL,
    base_reference TEXT,
    name TEXT NOT NULL,
    size TEXT,
    color TEXT,
    barcode TEXT,
    gender TEXT DEFAULT '',
    garment_code TEXT DEFAULT '',
    garment_type TEXT DEFAULT '',
    store_count INTEGER DEFAULT 0,
    warehouse_count INTEGER DEFAULT 0,
    theoretical_count INTEGER DEFAULT 0,
    difference INTEGER DEFAULT 0,
    category TEXT DEFAULT 'General',
    status TEXT DEFAULT 'pendiente', -- 'pendiente', 'validada'
    validation_verdict TEXT DEFAULT '',
    validation_notes TEXT DEFAULT '',
    validated_at TIMESTAMPTZ
);

-- 3. TABLA DEL CATÁLOGO UNIVERSAL DE FOTOS
CREATE TABLE IF NOT EXISTS catalog_photos (
    reference TEXT PRIMARY KEY,
    photo_url TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ÍNDICES DE ALTO RENDIMIENTO PARA CONSULTAS RÁPIDAS
CREATE INDEX IF NOT EXISTS idx_audit_items_audit_id ON audit_items(audit_id);
CREATE INDEX IF NOT EXISTS idx_audit_items_ref ON audit_items(reference);
CREATE INDEX IF NOT EXISTS idx_audit_items_base_ref ON audit_items(base_reference);
CREATE INDEX IF NOT EXISTS idx_audit_items_barcode ON audit_items(barcode);
CREATE INDEX IF NOT EXISTS idx_audits_date ON audits(audit_date DESC);

-- 5. POLÍTICAS DE ACCESO (ROW LEVEL SECURITY - RLS)
-- Habilitar RLS pero permitir acceso completo con clave anónima o autenticada
ALTER TABLE audits ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_photos ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura y escritura públicas para la app FARO
CREATE POLICY "Permitir lectura publica de audits" ON audits FOR SELECT USING (true);
CREATE POLICY "Permitir insercion y modificacion de audits" ON audits FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica de audit_items" ON audit_items FOR SELECT USING (true);
CREATE POLICY "Permitir insercion y modificacion de audit_items" ON audit_items FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica de catalog_photos" ON catalog_photos FOR SELECT USING (true);
CREATE POLICY "Permitir insercion y modificacion de catalog_photos" ON catalog_photos FOR ALL USING (true);

-- ============================================================================
-- STORAGE BUCKET PARA FOTOS DE PRENDAS (Ejecutar en Supabase Storage)
-- Nombre del bucket recomendado: "garment-photos"
-- Acceso: "Public bucket" (para que las fotos se puedan ver en cualquier celular)
-- ============================================================================
